---
- name: Install requirements
  apt: pkg={{ item }} state=present
  with_items:
    - make
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm

- name: clone pyenv
  git: repo=https://github.com/yyuu/pyenv.git dest=/usr/local/pyenv

- file: dest=/usr/local/pyenv owner=ubuntu group=ubuntu state=directory recurse=yes

- copy: src=pyenv.sh dest=/etc/profile.d/pyenv.sh owner=ubuntu group=ubuntu
