---
  - name: add docker repository key
    apt_key: keyserver=p80.pool.sks-keyservers.net id=58118E89F3A912897C070ADBF76221572C52609D

  - name: add repository
    apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present
