---
- hosts: all
  sudo: yes
  roles:
    - base
    - { role: rvm1-ansible, tags: ruby, sudo: True }
    - nodejs
    - oracle-jdk
    - golang
    - phantomjs
    - docker

  tasks:
    - mysql container
      docker:
        name: mysql
        image: tutum/mysql
        ports:
          - "3306:3306"
        env:
          MYSQL_PASS: admin
