---
- hosts: all
  sudo: yes
  roles:
    - base
    - oracle-jdk
    - golang
    - phantomjs
    - maven
    - pyenv
    - nodejs
    - docker.ubuntu
    - { role: rvm1-ansible, tags: ruby, become: yes, rvm1_gpg_keys: '' }

  tasks:
    - user: name=ubuntu groups=docker,rvm append=yes

    - name: mysql container
      docker:
        name: mysql
        image: tutum/mysql
        ports:
          - "3306:3306"
        env:
          MYSQL_PASS: admin

    - name: mongodb container
      docker:
        name: mongodb
        image: tutum/mongodb
        ports:
          - "27017:27017"
          - "28017:28017"
        env:
          AUTH: no

    - name: rabbitmq container
      docker:
        name: rabbitmq
        image: tutum/rabbitmq
        ports:
          - "5672:5672"
          - "15672:15672"
        env:
          RABBITMQ_PASS: admin

    - name: redis container
      docker:
        name: redis
        image: tutum/redis
        ports:
          - "6379:6379"
        env:
          REDIS_PASS: "**None**"

    - name: postgres container
      docker:
        name: postgres
        image: tutum/postgresql
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASS: postgres
