---
- hosts: all
  sudo: yes
  roles:
    - base
    - nodesource.node
    - oracle-jdk
    - golang
    - phantomjs
    - maven
    - pyenv

  tasks:
    - user: name=vagrant groups=docker,rvm,pyenv append=yes

    - name: Install docker-py as a workaround for Ansible issue
      pip: name=docker-py version=1.2.3

    - name: mysql container
      docker:
        name: mysql
        image: tutum/mysql
        ports:
          - "3306:3306"
        env:
          MYSQL_PASS: admin

    - name: mongodb container
      docker:
        name: mongodb
        image: tutum/mongodb
        ports:
          - "27017:27017"
          - "28017:28017"
        env:
          AUTH: no

    - name: rabbitmq container
      docker:
        name: rabbitmq
        image: tutum/rabbitmq
        ports:
          - "5672:5672"
          - "15672:15672"
        env:
          RABBITMQ_PASS: admin

    - name: redis container
      docker:
        name: redis
        image: tutum/redis
        ports:
          - "6379:6379"
        env:
          REDIS_PASS: "**None**"

    - name: postgres container
      docker:
        name: postgres
        image: tutum/postgresql
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASS: postgres
